export const GET_MONSTERS_BY_RATING = "GET_MONSTERS_BY_RATING";
export const CREATE_PLAYER = "CREATE_PLAYER";
export const GET_PLAYERS = "GET_PLAYERS";
export const CREATE_ENCOUNTER = "CREATE_ENCOUNTER";